### ISSUE TITLE
Sidebar? Oh it's down :(

### ISSUE THREAD

**Issue by vikmarino** [DigitalMindCH/twister-jekyll-theme#4]
I've finally discovered where's the sidebar. First I started by reading Docs and from there I understood that there's some sidebar. However when deploying the site locally, I see no sidebar. 
Just discovered the reason. If I open the site with 100% magnification of browser, the sidebar is not "side" but it's below the categories, pagination, etc. It's in the middle and not by side. 
In all browsers happens the same. With 90% it starts displaying it on the right side and it becomes real sidebar. But how to make it work with 100%? 

By _magnification_ I mean the cmd++ cmd-- on browser. I hope you understand me.

**Comment by halfapx** [comment]
What is your screen size? Categories etc. are within the sidebar and will only be displayed below the main content, if there is not enough space to fit the sidebar next to the content, as you can see in the demo page.

But there is some math involved, in case you changed something in the css that could also be the reason.

**Comment by vikmarino** [comment]
I have not touched css. My screensize is 13". Macbook pro. When I first go to the [site](http://digitalmind.ch/themes/twister-jekyll-theme/demo/), I see the logo, nav bar, and grid layout. There's no sidebar at all. When I click the 3rd icon in the top frame, the size changes and sidebar appears. However horizontal scroll is there now which is kind of ugly.

**Comment by halfapx** [comment]
Okay. I understand. I suppose you have a screen resolution that's smaller than 1330px then (something like: 1024 by 640). This means your screen is categorized as a tablet. The sidebar is collapsed if the screen is 1330px or smaller. you can change that though within the styling if that is what you want. This is not an issue though but actually wanted behavior. You can just take care of the collapses yourself if that is not what you wish to do, check out the sass files for that.

The reason why the size changes if you click on the icons is to demonstrate the different views. this is obviously not responsive, because you actually need the pixels in the width. Also this frame is not part of the theme, it is just part of the demonstration.
