### ISSUE TITLE
Deploying on github with plugins (not clear instructions)

### ISSUE THREAD

**Issue by vikmarino** [DigitalMindCH/twister-jekyll-theme#5]
Just some questions:

> But make sure that under no circumstances, your _site folder ends up on your .gitignore file, because **you need to build it yourself**, as the jekyll GitHub runs, would end up being a save build, so no plugins.

What you mean by yourself? You mean `grunt deploy` will do that?

> you want to create a branch called source and push **all of the things there**. 

all the things is the whole project? Or just **site_** generated folder?

> The site will then be copied into the master branch.
> So the whole thing is: 
> grunt will generate **site_** folder and push it to master branch?

I just can't understand the purpose of creating `source` brach.

> You might not want to push your node_modules folder, because it takes a lot of space and is not relevant

As I understand you don't recommend pushing this folder even to the "source" branch. But then how grunt will generate all the stuff? Maybe you want to say that we keep it under git but locally, not pushing it to server.

**Comment by halfapx** [comment]
okay, I will try to explain :)

So you have this whole project. All of that will be pushed to the source branch, except node_modules, which is a **huge** folder and should not be put to GitHub in General.
You will run grunt locally, it cannot be run on GitHub itself.
`grunt` (just the default comand) will run jekyll build as one of the tasks, so that's what will build the **_site** folder.

`grunt deploy` will take the _site folder, that has been generated before and move it to the master branch. That is all of the finished website so that it will be hosted by github pages.

The purpose of the source branch is version control. If you want to keep track of your changes within the code and on the site, you'll use the source branch. If you don't want that and just want github to host your site and backup all of the important files somewhere else, you could also skip the source branch.

**Comment by vikmarino** [comment]
Thanks
